name: 'salary job'

on:
  workflow_dispatch:
    inputs:
      actions:
        description: "action: start"
        default: "start"
  schedule:
    - cron: '0 17 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      - name: 'Install requirements'
        run: pip install -r requirements.txt
      - name: 'Run salary'
        env:
          CHAT_ID: ${{ secrets.CHAT_ID }}
          GZ_URL: ${{ secrets.GZ_URL }}
          PASS_WORD: ${{ secrets.PASS_WORD }}
          TEL_TOKEN: ${{ secrets.TEL_TOKEN }}
          USER_CODE: ${{ secrets.USER_CODE }}
          MYSQL_HOST: ${{ secrets.MYSQL_HOST }}
          MYSQL_PASS: ${{ secrets.MYSQL_PASS }}
        run: python salary.py
